[2024-06-14T04:29:22.637+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: ETL_toll_data.unzip_data manual__2024-06-14T04:28:29.633948+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
